stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - shell
  variables:
    PROJECT_DIR: "/home/root/projects/bisp-13292"
    GIT_STRATEGY: none  # Prevent automatic checkout
  script:
    - echo "Starting deployment..."
    - |
      if [ ! -d "$PROJECT_DIR" ]; then
        echo "❌ Directory $PROJECT_DIR does not exist"
        exit 1
      fi
    - cd $PROJECT_DIR
    - echo "✅ Pulling latest changes..."
    # Use CI_JOB_TOKEN for authentication
    - git remote set-url origin https://gitlab-ci-token:${CI_JOB_TOKEN}@${GITLAB_REMOTE_URL}
    - git pull origin main || { echo "❌ Git pull failed"; exit 1; }
    - echo "✅ Stopping existing containers..."
    - docker compose down || { echo "❌ Docker compose down failed"; exit 1; }
    - echo "✅ Starting new containers..."
    - docker compose up -d --build || { echo "❌ Docker compose up failed"; exit 1; }
    - echo "✅ Deployment completed successfully"
  after_script:
    # Reset remote URL to prevent token exposure
    - cd $PROJECT_DIR && git remote set-url origin https://${GITLAB_REMOTE_URL}
  only:
    - main